# Generated by Django 2.0.2 on 2019-07-29 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_auto_20190729_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diffytask',
            old_name='db_remark',
            new_name='remark',
        ),
    ]
